---

- hosts: chat_servers
  become: yes

  roles:
    - role: gray-monarch.common/install-swapfile
    - role: gray-monarch.common/update-system
    - role: RocketChat.Server
      rocket_chat_include_letsencrypt: true
      rocket_chat_tarball_check_checksum: false

  #  tasks:
  #  - include: tasks/cloudfront_patch.yml
  #    tags: patch
