---

- name: Apply the RocketChat.Server role to all chat_servers
  hosts: chat_servers
  vars:
        rocket_chat_tarball_sha256sum: 304fda849c49396b97253896a4e14b57ebc64698567bf609e5dfd4fd76dc63f4
        rocket_chat_automatic_upgrades: true
        rocket_chat_service_host: "{{ inventory_hostname }}"
  become: yes
  roles:
        - RocketChat.Server
