---

  - name: Patch rocketchat_file-upload.js for CloudFront URL Signing
    patch:
      src: cloudfront_URL_sig.patch
      dest: /var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_file-upload.js
    # This handler is in Role: Rocket.Chat.Server
    notify: Restart the Rocket.Chat service
