---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    ansible_requirements_loc: roles/requirements.yml

  tasks:
    - name: Install missing roles
      command: >-
          ansible-galaxy install
          --ignore-errors -r "{{ ansible_requirements_loc }}"
